[tox]
minversion = 3.10.0
envlist = py3{10,11,12,13}, format
isolated_build = true

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
commands = pytest tests -v
deps =
    pytest
    -r test-requirements.txt
setenv =
    PYTHONPATH = {toxinidir}

[testenv:format]
deps = ruff
commands = ruff format .